[package]
name = "aoc2020_rust"
version = "0.1.0"
authors = ["Jasper Pluijmers <jasper.pluijmers@nedap.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
